version: '3.8'
services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/LibraryDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - library-network

volumes:
  db_data:

networks:
  library-network:
